### ISSUE TITLE
Version 0.6.0 not published on crates.io

### ISSUE THREAD

**Issue by Karrq** [popzxc/alloy-zksync#32]
Seems like version `0.6.0` has not been published on crates.io: https://crates.io/crates/alloy-zksync

We [recently](https://github.com/matter-labs/foundry-zksync/pull/608) integrated `alloy-zksync` within `foundry-zksync` , using the published `0.5.0` version, but we are upgrading to a newer version of foundry, which makes use of alloy `0.6.0`, so we would need to use the equivalent `alloy-zksync` version.

Would be lovely to have this version published on crates.io like `0.5.0`. Thanks!

**Comment by popzxc** [comment]
Version 0.6.1 is published
